export const menuData = [
  {
    title: "Frühstück",
    items: [
      {
        id: "fr-1",
        name: "Spiegeleier mit Gemüse",
        price: 10,
        image: "/frn1.jpg",
        desc: "Serviert mit Ciabatta-Croutons",
      },
      {
        id: "fr-2",
        name: "Omlett",
        price: 11,
        image: "/frn2.jpg",
        desc: "Serviert mit Salat und Ciabatta-Croutons",
      },
      {
        id: "fr-3",
        name: "Rührei",
        price: 11,
        image: "/frn3.jpg",
        desc: "Serviert mit Salat und Ciabatta-Croutons",
      },
      {
        id: "fr-4",
        name: "Syrniki",
        price: 11,
        image: "/frn4.jpg",
        desc: "Serviert mit Sauerrahm und Konfitüre",
      },
    ],
  },

  {
    title: "Croissants",
    items: [
      {
        id: "cr-1",
        name: "Croissant mit Lachs",
        price: 9,
        image: "/crs1.jpg",
        desc: "Frischer Lachs, Ei, Salat, Sauce",
      },
      {
        id: "cr-2",
        name: "Croissant mit Hähnchen",
        price: 8,
        image: "/crs2.jpg",
        desc: "Hähnchen, Gemüse, hausgemachte Sauce",
      },
       {
        id: "cr-3",
        name: "Croissant mit Lachs",
        price: 9,
        image: "/crs3.jpg",
        desc: "Frischer Lachs, Ei, Salat, Sauce",
      },
    ],
  },

  {
    title: "Sandwiches",
    items: [
      {
        id: "sw-1",
        name: "Lachs-Sandwich im Ciabatta",
        price: 9,
        image: "/snd1.jpg",
        desc: "Mit Römersalat und Caesar-Dressing",
      },
      {
        id: "sw-2",
        name: "Hähnchen-Sandwich im Ciabatta",
        price: 8,
        image: "/snd2.jpg",
        desc: "Mit Römersalat und Caesar-Dressing",
      },
      {
        id: "sw-3",
        name: "Lachs-Sandwich im Croissant",
        price: 9,
        image: "/snd3.jpg",
        desc: "Mit Römersalat und Caesar-Dressing",
      },{
        id: "sw-4",
        name: "Hähnchen-Sandwich im Croissant",
        price: 8,
        image: "/snd4.jpg",
        desc: "Mit Römersalat und Caesar-Dressing",
      },
    ],
  },

  {
    title: "Salate",
    items: [
      {
        id: "sa-1",
        name: "Thunfischsalat",
        price: 11.5,
        image: "/sal1.jpg",
        desc: "Römersalat, Rucola, Kirschtomaten, Kalamata-Oliven, Gurke, Crumble, Passionsfrucht-Dressing",
      },
      {
        id: "sa-2",
        name: "Caesar Salat mit Hähnchen",
        price: 11.5,
        image: "/sal2.jpg",
        desc: "Römersalat, Kirschtomaten, Caesar-Dressing, Hähnchen, Parmesan-Crumble und knusprige Röstzwiebeln",
      },
       {
        id: "sa-3",
        name: "Veggie Salat",
        price: 11.5,
        image: "/sal3.jpg",
        desc: "Römersalat, Rucola, grüne Bohnen, Gurke, Paprika, Kirschtomaten, Nuss-Dressing. veganer Crumble",
      },
    ],
  },

  {
    title: "Hauptgerichte",
    items: [
      {
        id: "main-1",
        name: "Roastbeef",
        price: 18,
        image: "/delivery.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "main-2",
        name: "Lachs mit Reis",
        price: 18,
        image: "/delivery.jpg",
        desc: "Lachsfilet, Reis, Bohnen",
      },
      {
        id: "main-3",
        name: "Roastbeef",
        price: 18,
        image: "/delivery.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
    ],
  },
  {
    title: "Getränke",
    items: [
      {
        id: "gt-1",
        name: "Roastbeef",
        price: 18,
        image: "/gt1.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-2",
        name: "Lachs mit Reis",
        price: 18,
        image: "/gt2.jpg",
        desc: "Lachsfilet, Reis, Bohnen",
      },
      {
        id: "gt-3",
        name: "Roastbeef",
        price: 18,
        image: "/gt3.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-4",
        name: "Roastbeef",
        price: 18,
        image: "/gt4.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-5",
        name: "Roastbeef",
        price: 18,
        image: "/gt5.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-6",
        name: "Roastbeef",
        price: 18,
        image: "/gt6.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-7",
        name: "Roastbeef",
        price: 18,
        image: "/gt7.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-8",
        name: "Roastbeef",
        price: 18,
        image: "/gt8.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-9",
        name: "Roastbeef",
        price: 18,
        image: "/gt9.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-10",
        name: "Roastbeef",
        price: 18,
        image: "/gt10.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-11",
        name: "Roastbeef",
        price: 18,
        image: "/gt11.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-12",
        name: "Roastbeef",
        price: 18,
        image: "/gt12.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-13",
        name: "Roastbeef",
        price: 18,
        image: "/gt13.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-14",
        name: "Roastbeef",
        price: 18,
        image: "/gt14.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-15",
        name: "Roastbeef",
        price: 18,
        image: "/gt15.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-16",
        name: "Roastbeef",
        price: 18,
        image: "/gt16.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-17",
        name: "Roastbeef",
        price: 18,
        image: "/gt17.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-18",
        name: "Roastbeef",
        price: 18,
        image: "/gt18.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-19",
        name: "Roastbeef",
        price: 18,
        image: "/gt19.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-20",
        name: "Roastbeef",
        price: 18,
        image: "/gt20.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-21",
        name: "Roastbeef",
        price: 18,
        image: "/gt21.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-22",
        name: "Roastbeef",
        price: 18,
        image: "/gt22.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-23",
        name: "Roastbeef",
        price: 18,
        image: "/gt23.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },
      {
        id: "gt-24",
        name: "Roastbeef",
        price: 18,
        image: "/gt24.jpg",
        desc: "Mit Ofenkartoffeln & Gemüse",
      },

      
    ],
  },
  
];